# Generated by Django 4.1 on 2022-08-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviate_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Qualificaiton',
            new_name='qualificaiton',
        ),
        migrations.AddField(
            model_name='jobs',
            name='experience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
