# Generated by Django 4.1 on 2022-08-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviate_app', '0002_rename_qualificaiton_jobs_qualificaiton_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='qualificaiton',
            new_name='qualification',
        ),
    ]
