# Generated by Django 4.1 on 2022-08-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviate_app', '0004_remove_jobapplication_last_edu_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
