# Generated by Django 4.1 on 2022-08-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviate_app', '0005_jobapplication_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='candidate_exp',
        ),
    ]
